version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"  
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
        - "5000:5000"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: ak
      MYSQL_PASSWORD: ak123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql 

volumes:
  mysql-data:  

